/**
 * OLO web instrument catalog.
 * @typedef {{ title: string, href: string, tag: string, blurb: string, origin: string }} HubApp
 */

/** @type {HubApp[]} */
export const HUB_APPS = [
  {
    title: "CliX",
    href: "apps/clix/",
    tag: "Rhythm",
    blurb: "Hold keyboard keys; an 8×4 grid retriggers typed impulses (Ge Wang / OLO CliX).",
    origin: "Port of patches/pieces/CliX · adapted from OMO",
  },
  {
    title: "Crystalis",
    href: "apps/crystalis/",
    tag: "Melody",
    blurb: "Bow or pluck pentatonic lines; trackpad bowing and synced grid (OLO Crystalis).",
    origin: "Port of patches/pieces/Crystalis · adapted from OMO",
  },
  {
    title: "Droner",
    href: "apps/droner/",
    tag: "Drone",
    blurb: "Four harmonic corners crossfaded with the pointer; keys 1–8 change pitch (Dan Trueman).",
    origin: "Port of patches/pieces/Droner",
  },
  {
    title: "Clap Hands",
    href: "apps/clap-hands/",
    tag: "Texture",
    blurb: "Mic-driven multi-tap delay — clap or speak into the laptop (OLO ClapHands).",
    origin: "Port of patches/pieces/ClapHands",
  },
  {
    title: "Munge",
    href: "apps/munge/",
    tag: "Texture",
    blurb: "Live mic into a feedback delay cloud (PLOrk munging / OLO MungingMunger).",
    origin: "Inspired by patches/pieces/MungingMunger",
  },
  {
    title: "Tap Bloom",
    href: "apps/tap-bloom/",
    tag: "Texture",
    blurb: "Click to plant pentatonic tones that pulse every four seconds with long reverb.",
    origin: "Laptop version of OMO Tap Bloom",
  },
  {
    title: "Green Button",
    href: "apps/green-button/",
    tag: "Drone",
    blurb: "Hold the button (or spacebar) for a swelling sine drone with gentle vibrato.",
    origin: "Laptop version of OMO Green Button",
  },
  {
    title: "XY-FM",
    href: "apps/xy-fm/",
    tag: "Synthesis",
    blurb: "Full-screen FM pad — mouse X/Y = pitch and depth; keys 1–4 switch routing.",
    origin: "OMO FM Matrix / Kaoss Pad · laptop",
  },
  {
    title: "Horizon",
    href: "apps/horizon/",
    tag: "Drone",
    blurb: "Shepard tone across the screen — tilt or vertical drag; Space to play.",
    origin: "OMO Shepard Glide · laptop",
  },
  {
    title: "Slice Keys",
    href: "apps/slice-keys/",
    tag: "Sampler",
    blurb: "Record mic (R), keys 1–8 play slices; drag to scrub while holding.",
    origin: "OMO Sampler / Scrub Tape · laptop",
  },
  {
    title: "Vision Grain",
    href: "apps/vision-grain/",
    tag: "Granular",
    blurb: "Camera motion spawns grains; A/S/D/F tweak size and pitch spread.",
    origin: "OMO Video Sonifier · laptop",
  },
  {
    title: "Circular Groove",
    href: "apps/circular-groove/",
    tag: "Rhythm",
    blurb: "Euclidean rings with phase shifts; L-system rules evolve the pattern each bar.",
    origin: "OMO Euclidean Rings + L-System Groove · laptop",
  },
  {
    title: "Beat Matrix",
    href: "apps/beat-matrix/",
    tag: "Rhythm",
    blurb: "Full-screen 16-step grid; QWERTY keys toggle steps while you play.",
    origin: "Laptop step sequencer",
  },
  {
    title: "Shiny Machine",
    href: "apps/shiny-machine/",
    tag: "Rhythm",
    blurb: "16-step drum machine — kits, swing, convolution effects, tri-level velocity per step.",
    origin: "Inspired by Chrome Labs WebAudio Drum Machine · synthesized",
  },
  {
    title: "Filter Ladder",
    href: "apps/filter-ladder/",
    tag: "Synthesis",
    blurb: "Saw through a 4-pole ladder; tilt or mouse Y opens the filter.",
    origin: "OMO Filter Ladder · laptop",
  },
  {
    title: "Mic Theremin",
    href: "apps/mic-theremin/",
    tag: "Melody",
    blurb: "Hum into the mic; pitch-tracked sine with vibrato from mouse X.",
    origin: "OMO Mic Theremin · laptop",
  },
  {
    title: "Room Wash",
    href: "apps/room-wash/",
    tag: "Texture",
    blurb: "Mic loudness sends the room into long convolution reverb.",
    origin: "OMO Room Reverb Send · laptop",
  },
  {
    title: "Shadow Seq",
    href: "apps/shadow-seq/",
    tag: "Rhythm",
    blurb: "Webcam split into 8 zones; darkness = steps on a running clock.",
    origin: "OMO Shadow Sequencer · laptop",
  },
  {
    title: "Wavetable Scan",
    href: "apps/wavetable-scan/",
    tag: "Synthesis",
    blurb: "Hold the pad; X morphs waveshapes, Y = pitch and level.",
    origin: "OMO Wavetable Scan · laptop",
  },
  {
    title: "Autophagy",
    href: "apps/autophagy/",
    tag: "Texture",
    blurb: "Sonify cellular starvation and autophagy — nutrients, phases, lysosomal recycling.",
    origin: "Biology × laptop performance · nutrient stress sonification",
  },
];
